# Generated by Django 2.2.1 on 2019-06-06 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seizure', '0001_initial'),
        ('medication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication', models.ManyToManyField(to='medication.Medication')),
                ('seizure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seizure.Seizure')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
